### ISSUE TITLE
Some rare items and large charms not shown

### ISSUE THREAD

**Issue by arsirantala** [Boxcar87/Greedygoblin#1]
Hiya,

And thanks for nice filter - I like it, nice when one wants to farm gold :)

Two things, I noted that some rare items (gothic armor it was if I remember correctly) were not shown nor large charms - especially large charms are in my opinion worth showing don't you agree?

**Comment by Boxcar87** [comment]
Large charms are pretty much worthless once you reach hell. Smalls and
grands are superior. Rare weapons disappear after 60, class gear is the
only exception

**Comment by arsirantala** [comment]
> Large charms are pretty much worthless once you reach hell. Smalls and
> grands are superior. Rare weapons disappear after 60, class gear is the
> only exception

Not entirely worthless - got one large charm which had 34 life, which is not of course max 40 hp, but good enough for me in relatively early ladder 😀 but hey I am casual.

Anyway point taken, case closed and keep up the good work. Looking forward on updates on the filter.
